name: Deploy on Main Push

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "firebase.json"
      - "package.json"
      - "index.html"
      - "vitest.config.js"
      - ".firebaserc"
      - ".github/workflows/*"

concurrency:
  group: firebase-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: 🛠️ Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🛠️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: 📂 Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-

      - name: 📂 Install Packages
        run: npm ci

      - name: 🧱 Inject Environment Variables
        run: |
          echo "VITE_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env

      - name: 🧱 Build Project
        run: npm run build

      - name: 🚀 Deploy to Firebase
        if: success()
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_YES_CHEF_E36A7 }}"
          projectId: yes-chef-e36a7
          channelId: live
